### ISSUE TITLE
EtcdCluster API grooming

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1719]
As part of the roadmap to stable (1.0) EtcdCluster API, we need to cleanup unnecessary fields and clarify/improve some fields.

Task list:
- [ ] ClusterSpec.BaseImage (https://github.com/coreos/etcd-operator/issues/1675): It would be renamed to "Repository", and would be made clear that the images are supposed to be a clone of upstream etcd images (quay.io/coreos/etcd or gcr.io/etcd-development/etcd). It is used to support private cluster/offline operation use cases.
- [ ] ClusterSpec.PodPolicy.AntiAffinity would be deprecated and more general Affinity type should be used (https://github.com/coreos/etcd-operator/issues/1676)
- [ ] ClusterSpec.PodPolicy.AutomountServiceAccountToken would be deprecated and by default we would disable that on etcd pods.
- [ ] ClusterSpec.SelfHostedPolicy should be put behind a feature gate. By default normal app etcd cluster could not touch it.
- [ ] ClusterStatus.Reason would be replaced by a new Condition "Failed" 
- [ ] ClusterStatus.ControlPaused would be removed (https://github.com/coreos/etcd-operator/issues/1313).

**Comment by hongchaodeng** [comment]
For 0.7.1, we will fix the first three items.
The rest three will be fixed in the following release.

**Comment by raoofm** [comment]
@hongchaodeng gentle reminder to update milestones 😄  for existing issues.

**Comment by raoofm** [comment]
@hongchaodeng The below item should be removed from the list of pending items for this issue as self hosted isn't in scope anymore.

> ClusterSpec.SelfHostedPolicy should be put behind a feature gate. By default normal app etcd cluster could not touch it.

**Comment by raoofm** [comment]
ping?

**Comment by hongchaodeng** [comment]
@raoofm 
All of our team members are dedicated on a private project (probably will open source, not sure) by end of Feb.
I can spend time grooming issues early next week.

**Comment by raoofm** [comment]
@hongchaodeng is this being prioritized anytime soon.

> All of our team members are dedicated on a private project (probably will open source, not sure) by end of Feb.

Is this open sourced, name?

**Comment by raoofm** [comment]
@xiang90 @hongchaodeng @fanminshi @gyuho @hasbro17 @philips 
Just want to know if there will be any progress on etcd-operator or is it marked as stale internally and will progress only by community contribution and not by coreos. It would be better to know if it makes sense to wait for this to be stable or go ahead with some other route.

**Comment by philips** [comment]
This project will continue to be invested in. The team who maintains it at Red Hat is currently busy with other projects at the moment however.

**Comment by raoofm** [comment]
@philips awesome :+1:, thank you. Its really important to know the roadmap. Thanks for replying though, great work guys
